# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.4.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - run: sudo apt install libsasl2-dev
      - run: sudo npm install --global yarn@^1.3.2
      - checkout
      - run: yarn install
      - run: node_modules/gulp/bin/gulp.js
      - deploy:
          name: Publish to private npm registry
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm pack
              package="$(npm ls --depth=0 | head -n 1 | cut -d ' ' -f 1 | sed s/\@/-/)"
              curl -F package=@${package}.tgz $NPM_PUSH_URL
            fi
